packages:
  - "packages/*"

catalog:
  "@typescript-to-lua/language-extensions": ~1.19.0
  "@typed-tabletop-simulator/declaration": ~2.0.3
  "@typed-tabletop-simulator/ui": ^0.4.0
  arktype: ~2.0.0
  rimraf: ~6.0.1
  typescript: 5.7.2
  typescript-to-lua: ~1.30.1
  vitest: ~2.1.8
